import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import {
	LineChart,
	Line,
	XAxis,
	YAxis,
	CartesianGrid,
	Tooltip,
	Legend
} from 'recharts';
import moment from 'moment';
export default function Home() {
	var day = moment('2022-04-13');

	const newSet = data.data.map(
		(d, i) =>
			(d = {
				value: d,
				date: moment()
					.add(i, 'days')
					.format('MMM Do YY')
			})
	);
	console.log(newSet);
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>Will
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<div>
					<LineChart width={1300} height={400} data={newSet}>
						<CartesianGrid strokeDasharray="3 3" />
						<XAxis />
						<YAxis interval="preserveEnd" />
						<Legend />
						<Line
							type="monotone"
							dataKey="value"
							stroke="#8884d8"
							activeDot={{ r: 8 }}
						/>
					</LineChart>
				</div>
			</main>
			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by Vercel and Replit
				</a>
			</footer>
		</div>
	);
}

export const data = {
	data: [
		248,
		248,
		248,
		248,
		248,
		248,
		248,
		106,
		106,
		106,
		106,
		106,
		106,
		106,
		300,
		300,
		300,
		300,
		300,
		300,
		300,
		375,
		375,
		375,
		375,
		375,
		375,
		375,
		145,
		145,
		145,
		145,
		145,
		145,
		145
	],
	msg: {
		code: 2000,
		msg: 'OK'
	},
	success: true
};
