import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import {
	BarChart,
	CartesianGrid,
	YAxis,
	XAxis,
	Tooltip,
	Legend,
	Bar
} from 'recharts';
import dataOne from '../components/data.js';

export default function Home() {
	const data = [
		{ pv: '500', uv: 650, date: '12-10-22' },
		{ pv: '300', uv: 650, date: '12-10-22' }
	];

	const { name } = dataOne.result.objects;
	const { value } = dataOne.result.objects;
	const { unit } = dataOne.result.objects;

	const newSet = name.map((d, i) => (d = [d, value[i]]));
	const entries = new Map(newSet);
	const obj = Object.fromEntries(entries);
	obj.date = '12-10-22';
	console.log(obj);

	const datad = [
		{
			ripe: 143,
			full: 49,
			mid: 165,
			small: 195,
			tiny: 79,
			flower: 221,
			damage: 0,
			chlorosis: 0,
			dieoff: 0,
			date: '12-10-22'
		},
		{
			full: 16,
			mid: 165,
			small: 88,
			tiny: 79,
			flower: 221,
			damage: 0,
			chlorosis: 0,
			dieoff: 0,
			date: '14-10-22'
		},
		{
			ripe: 80,
			full: 60,
			mid: 124,
			small: 88,
			tiny: 79,
			flower: 221,
			damage: 0,
			chlorosis: 0,
			dieoff: 0,
			date: '16-10-22'
		},
		{
			ripe: 98,
			full: 60,
			mid: 124,
			small: 88,
			tiny: 79,
			flower: 221,
			damage: 0,
			chlorosis: 0,
			dieoff: 0,
			date: '16-10-22'
		},
		{
			ripe: 130,
			full: 60,
			mid: 124,
			small: 88,
			tiny: 79,
			flower: 221,
			damage: 0,
			chlorosis: 0,
			dieoff: 0,
			date: '16-10-22'
		}
	];

	const BarColors = {
		ripe: '#EA4335',
		full: '#FF9900',
		mid: '#E6B8AF',
		small: '#50B46B',
		flower: '#FCE5CD'
	};
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>Will
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<div>
					<BarChart width={730} height={400} data={datad}>
						<CartesianGrid strokeDasharray="3 3" />
						<XAxis dataKey="date" />
						<YAxis />
						<Tooltip />
						<Legend />
						<Bar dataKey="ripe" fill={BarColors.ripe} />
						<Bar dataKey="full" fill={BarColors.full} />
						<Bar dataKey="mid" fill={BarColors.mid} />
						<Bar dataKey="small" fill={BarColors.small} />
						<Bar dataKey="flower" fill={BarColors.flower} />
					</BarChart>
				</div>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by Vercel and Replit
				</a>
			</footer>
		</div>
	);
}
